version: "3"
services:
  my-app:
    image: abbyz/docker-abby:${IMAGE_VERSION}-local
    depends_on:
      - db
    # command: ["./node_modules/.bin/nodemon", "app.js"]
    command: ["npm","run","dev"]
    container_name: my-app
    volumes:
      - ".:/app/:rw"
    env_file: .env
    environment:
      NODE_ENV: development
    ports:
      - "5000:${PORT}"
      - "3000:3000"
    networks:
      - my-app-network
  db:
    image: postgres:10.0-alpine
    env_file: .env
    volumes: 
      - pg-data-volume:/var/lib/postgresql/data
    ports: 
      - '${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}'
    networks:
      - my-app-network
volumes: 
  pg-data-volume:
networks:
  my-app-network: